---
title: "SS26 SM1: Sprachverarbeitung und Spracherwerb aus typologischer Sicht"
format: html
editor: source
bibliography: references.bib
---

# Kursbeschreibung

**Kursleiterin**: Eva Scheel(-Huber)

**Email-Adresse**: eva.scheel-huber(at)uni-koeln(dot)de

Wie verarbeiten und lernen Menschen Sprache auf der ganzen Welt? In diesem Kurs nähern wir uns diesen Themen aus typologischer Sicht. Wir schauen uns an, wie Menschen Sätze verarbeiten, produzieren und lernen und wie diese Prozesse sich zwischen Sprecher\*innen unterschiedlicher Sprachen ähneln und unterscheiden. Den Fokus legen wir dabei auf Morphosyntax. Themen umfassen unter anderem wie die eigene Sprache die Produktion, das Verstehen und Erlernen von Sätzen in unterschiedlichen Worstellungen beeinflussen. Zuerst erarbeiten wir uns die nötigen Grundlagen der Methodologien und Theorien der Psycholinguistik und besprechen im Anschluss Papers aus Fachzeitschriften. Der Kurs wird ebenfalls einen praktischen Teil beinhalten.

# Semesterplan

+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| Sitzung    | Datum      | Thema                                                         | Lektüre                                           | Zusätzliche Lektüre                                                |
+============+============+===============================================================+===================================================+====================================================================+
| 1          | 16.04.2026 | [Einführung](Sitzung_1.html)                                  |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 2          | 23.04.2026 | Sprachdiversität in der Psycholinguistik                      | @norcliffeCrosslinguisticPsycholinguisticsIts2015 | @stoll2015; @passmore2025; @henrich2010; @bowerman2010; @blasi2022 |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 3          | 30.04.2026 | Sprachverstehen Erwachsene; "Competition Model"               | @macwhinney1984                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 4          | 07.05.2026 | Spracherwerb; "Competition Model"                             | @chan2009                                         |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| \-         | 14.05.2026 | Christi Himmelfahrt                                           |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 5          | 21.05.2026 | Sprachverstehen Erwachsene; Agens Präferenz                   | @sauppe2022                                       | @demiral2008; @bickel2015; @isasi-isasmendi2024                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| \-         | 28.05.2026 | Pfingstferien                                                 |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| \-         | 04.06.2026 | Fronleichnam                                                  |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 6          | 11.06.2026 | Spracherwerb; Agens Präferenz                                 | @abbot-smith2017                                  | @shin2019                                                          |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 7          | 18.06.2026 | Sprachverstehen Erwachsene & Kinder; Passiv oder Relativsätze |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 8          | 25.06.2026 | Sprachproduktion & Satzplanung Erwachsene                     |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 9          | 02.07.2026 | Vorbereitung Leistungsnachweis B individuell zuhause          |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 10         | 09.07.2026 | Vorstellen Leistungsnachweis B                                |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 11         | 16.07.2026 | Input zu wissenschaftlichem Schreiben                         |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+
| 12         | 23.07.2026 | Vorstellen Leistungsnachweis B                                |                                                   |                                                                    |
+------------+------------+---------------------------------------------------------------+---------------------------------------------------+--------------------------------------------------------------------+

# Referenzen