---
title: "SS26 SM1: Gemeinsame Werte, Wünsche, Erwartungen"
format: html
---


### Atmosphäre, Umgang

- respektvoller, lockerer Umgang miteinander ohne Vorurteile 
- freie Atmosphäre, wo alle reinreden dürfen, wenn sie eine Frage, Anmerkung, o.Ä. haben


### Seminarstruktur

- Aufbau von Grundlagen, also viel theoretische Arbeit
- aktive Gespräche und Ideenaustausch zwischen Dozentin und Kommilitonen
- rege Plenumsdikussionen
- Frontalunterricht (Theorie) + Anwendungsbeispielen, Übungen für die Anwendung des angeeigneten Wissens, verschiedene wissenschaftliche Lektüren zu den Themen
- Gruppenarbeiten für Diskussionen
- Gruppenarbeiten mit selbst ausgewählten Kommiliton:innen anstelle Zufallsprinzip 
- gute, kohärente Struktur
    - Klarheit über Studienleistungen & Modulabschlussprüfung
    - Seminarplan
- Fragerunden zu den Texten 
- gut organisierte ILIAS-Seite
- Feedback zu Studienleistungen, Besprechung der Antworten

### Ziele

- mehr über Psycholinguistik zu lernen
- Prozesse und Methoden verstehen
- Möglichkeit auch asynchron Inhalte zu verstehen

